version: "3.7"

services: 
  client:
    container_name: mock_server_client
    image: iamkira/mock-server_client
    build: ./client
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./client/src:/app/src
    depends_on:
      - backend
    restart: always
    
  backend:
    container_name: mock_server_backend
    image: iamkira/mock-server_backend
    build: ./backend
    ports: 
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./backend:/app
    restart: always